# NumPy Basics

**Course:** Nonlinear Dynamics and Chaos with Python  
**Length:** 2 hours (in-class) — Colab-friendly, focused on numerical tools (no plotting).

**Learning objectives (by the end of this notebook):**
- Create and inspect NumPy arrays (1D & 2D), understand `dtype`, `shape`, and `ndim`.  
- Index, slice, and mask arrays; grasp boolean indexing.  
- Use vectorized arithmetic and broadcasting for concise numerical code.  
- Reshape and manipulate arrays (`reshape`, `ravel`, `stack`, `transpose`).  
- Use `np.linalg` for dot products and solving linear systems.  
- Generate random numbers with NumPy's `default_rng`.  
- Implement a small vectorized simulation (iterated map) and compute simple diagnostics.

## Quick start — imports and sanity checks

In [1]:
# Standard imports for this notebook
import numpy as np
import time
from math import isclose

print("NumPy version:", np.__version__)

NumPy version: 2.3.5


### Quick demo: Why NumPy? (vectorized speed comparison)

In [2]:
N = 200_000
x_list = list(range(N))
x_arr = np.arange(N)

t0 = time.time()
y_list = [xi*xi for xi in x_list]    # Python list comprehension
t1 = time.time()

t2 = time.time()
y_arr = x_arr * x_arr                # NumPy vectorized multiplication
t3 = time.time()

print("Python list comp: {:.3f} s".format(t1-t0))
print("NumPy vectorized: {:.3f} s".format(t3-t2))
print("First 5 results equal?:", y_list[:5] == y_arr[:5].tolist())

Python list comp: 0.010 s
NumPy vectorized: 0.001 s
First 5 results equal?: True


So, there is an order of magnitude reduction in time

## 1) Array creation and basic attributes

In [3]:
# Array creation examples
a = np.array([1, 2, 3])           # from Python list
zeros = np.zeros(6)               # zeros
ones = np.ones((2,3))             # 2x3 array of ones
full = np.full(5, 7.0)            # filled array with float
ar = np.arange(0, 10, 2)          # like range: start, stop (exclusive), step
lin = np.linspace(0.0, 1.0, 5)    # inclusive spacing

for name, arr in [("a",a),("zeros",zeros),("ones",ones),("full",full),("ar",ar),("lin",lin)]:
    print(f"{name}: shape={arr.shape}, ndim={arr.ndim}, size={arr.size}, dtype={arr.dtype}")

a: shape=(3,), ndim=1, size=3, dtype=int64
zeros: shape=(6,), ndim=1, size=6, dtype=float64
ones: shape=(2, 3), ndim=2, size=6, dtype=float64
full: shape=(5,), ndim=1, size=5, dtype=float64
ar: shape=(5,), ndim=1, size=5, dtype=int64
lin: shape=(5,), ndim=1, size=5, dtype=float64


### `dtype` matters — memory & behaviour

In [4]:
# dtype examples
mix = np.array([1, 2.0, 3])   # promotes to float
print("mix dtype:", mix.dtype)

s = np.array([1,2,3], dtype=np.int32)
f = s.astype(np.float64)      # explicit cast
print("s.dtype ->", s.dtype, "f.dtype ->", f.dtype)

mix dtype: float64
s.dtype -> int32 f.dtype -> float64


## 2) Indexing, slicing and boolean masking

In [5]:
# 1D indexing and slicing
x = np.arange(10)
print("x:", x)
print("x[2:7]:", x[2:7])
print("x[::-1] (reverse):", x[::-1])

# 2D indexing
A = np.arange(1,10).reshape(3,3)
print("\nA:\n", A)
print("A[0,0], A[:,1], A[1,:] ->", A[0,0], A[:,1], A[1,:])

# Boolean indexing (masking)
mask = x % 2 == 0
print("\nx even mask:", mask)
print("x[mask]:", x[mask])

x: [0 1 2 3 4 5 6 7 8 9]
x[2:7]: [2 3 4 5 6]
x[::-1] (reverse): [9 8 7 6 5 4 3 2 1 0]

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A[0,0], A[:,1], A[1,:] -> 1 [2 5 8] [4 5 6]

x even mask: [ True False  True False  True False  True False  True False]
x[mask]: [0 2 4 6 8]


## 3) Vectorized operations & broadcasting (the core)

In [6]:
# Vectorized arithmetic
x = np.arange(5)
print("x:", x)
print("x + 10 ->", x + 10)
print("x * 2 ->", x * 2)
print("np.sin(x) ->", np.sin(x))   # ufunc example

# Broadcasting example
M = np.ones((3,4))
b = np.arange(4)
print("\nM + b ->\n", M + b)

x: [0 1 2 3 4]
x + 10 -> [10 11 12 13 14]
x * 2 -> [0 2 4 6 8]
np.sin(x) -> [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]

M + b ->
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## 4) Reshape and array manipulation

In [7]:
# Reshape, transpose, flatten, stack
arr = np.arange(12)
A = arr.reshape(3,4)
print("A.shape:", A.shape)
print("A:\n", A)
print("A.T:\n", A.T)
print("A.ravel() ->", A.ravel())

# stacking
a = np.array([1,2,3])
b = np.array([4,5,6])
print("\nhstack:", np.hstack([a,b]))
print("vstack:\n", np.vstack([a,b]))

A.shape: (3, 4)
A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A.T:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
A.ravel() -> [ 0  1  2  3  4  5  6  7  8  9 10 11]

hstack: [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]


## 5) Linear algebra with `np.linalg` (practical subset)

In [13]:
# Dot product, matrix multiplication, solve linear system
x = np.array([1,2,3])
y = np.array([0,1,0])
print("dot:", np.dot(x,y))
print("x @ y (same but for arrays with >=1D):", x @ y)

A = np.array([[3.0,1.0],[1.0,2.0]])
B = np.array([[1.0,2.0],[2.0,3.0]])
b = np.array([9.0,8.0])
print("\nA:\n", A)
print("\nB:\n", B)
print("\ndet(A):", np.linalg.det(A))
print("\nA @ B:\n", A @ B)
sol = np.linalg.solve(A, b)
print("\nsolve(A,b) ->", sol)
print("Check A @ sol ->", A @ sol)

dot: 2
x @ y (same but for arrays with >=1D): 2

A:
 [[3. 1.]
 [1. 2.]]

B:
 [[1. 2.]
 [2. 3.]]

det(A): 5.000000000000001

A @ B:
 [[5. 9.]
 [5. 8.]]

solve(A,b) -> [2. 3.]
Check A @ sol -> [9. 8.]


## 6) Random numbers

In [14]:
# Use the newer Generator API
rng = np.random.default_rng(12345)   # seed for reproducibility
print("uniform 5:", rng.random(5))
print("normal 100 mean:", rng.normal(0,1,100).mean())
print("integers 0-9:", rng.integers(0,10,10))

uniform 5: [0.22733602 0.31675834 0.79736546 0.67625467 0.39110955]
normal 100 mean: -0.03062500911899471
integers 0-9: [9 3 2 5 0 3 1 2 1 2]


## 7) Mini-project (in-class): Logistic map time series — compute diagnostics (no plotting)

We will implement the logistic map iterate and compute simple stats & return the last `m` values as a NumPy array. This demonstrates combining loops (or vectorized ideas) with arrays and preparing data for later plotting notebook.

In [ ]:
def logistic_iterate(r, x0, n):
    '''Return a NumPy array of length n of logistic iterates starting from x0.'''
    xs = np.empty(n, dtype=float)
    xs[0] = x0
    for i in range(n-1):
        xs[i+1] = r * xs[i] * (1 - xs[i])
    return xs

# Example usage
r = 3.7
x0 = 0.2
N = 500
xs = logistic_iterate(r, x0, N)

print("First 8 iterates:", xs[:8])
print("Last 8 iterates:", xs[-8:])
print("Mean of last 100 iterates:", xs[-100:].mean())
print("Std of last 100 iterates:", xs[-100:].std())

## Exercises (in-class, short)

Attempt these quickly. Solutions are provided in the following cells.

1. **Vectorized square**: Given `a = np.arange(1,101)`, compute `a**2` and verify the 50th element equals 2500 using an assert.

2. **Masking**: Create an array `t = np.linspace(0, 2*np.pi, 13)` and use boolean masking to extract values where `sin(t) > 0.5`.

3. **Reshape puzzle**: Create `b = np.arange(24)` and reshape to `(4,6)`. Then extract the 3rd column as a 1D array.

4. **Linear solve check**: Solve a 3x3 system `A x = b` where `A = np.array([[3,2,1],[1,1,1],[1,0,2]])` and `b = np.array([1,2,3])`. Verify the solution by computing `A @ x`.

### Solutions (run these cells to check)

In [20]:
# 1. Vectorized square
a = np.arange(1,101)
a2 = a**2
assert a2[49] == 2500, "You have made a wrong assertion" # Check what happens if you make a wrong assertion
print("Exercise 1 OK: 50th element =", a2[49])

Exercise 1 OK: 50th element = 2500


In [21]:
# 2. Masking
t = np.linspace(0, 2*np.pi, 13)
vals = t[np.sin(t) > 0.5]
print("t values where sin(t) > 0.5:", vals)

t values where sin(t) > 0.5: [1.04719755 1.57079633 2.0943951  2.61799388]


In [22]:
# 3. Reshape puzzle
b = np.arange(24).reshape(4,6)
col3 = b[:,2]
print("3rd column:", col3)

3rd column: [ 2  8 14 20]


In [23]:
# 4. Linear solve
A = np.array([[3,2,1],[1,1,1],[1,0,2]], dtype=float)
b = np.array([1,2,3], dtype=float)
x = np.linalg.solve(A,b)
print("solution x:", x)
print("A @ x ->", A @ x)
assert np.allclose(A @ x, b)
print("Exercise 4 OK")

solution x: [-1.  1.  2.]
A @ x -> [1. 2. 3.]
Exercise 4 OK


## Tips & best practices (short)

- Avoid Python loops over large arrays — use vectorized operations.  
- Prefer `np.random.default_rng()` over legacy `np.random` for reproducibility.  
- When performance matters, check `arr.dtype` — using `float32` vs `float64` can save memory.  
- Use `np.testing.assert_allclose()` or `np.allclose()` for floating-point checks.  
- Keep shape / broadcasting rules in mind; when shapes mismatch, NumPy will try broadcasting.

## Where next

In the next notebook we'll cover **Matplotlib** and visualisations: how to plot time series, phase portraits, bifurcation diagrams, scatter plots of attractors, and presentation-quality figures suitable for a course in nonlinear dynamics.  